# Generated by Django 4.2 on 2023-05-22 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, max_length=4, verbose_name="код"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "СМС код",
                "verbose_name_plural": "СМС коды",
            },
        ),
    ]
