# Generated by Django 4.2 on 2023-05-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_servicetype_service_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Тип услуги', 'verbose_name_plural': 'Типы услуг'},
        ),
        migrations.RemoveField(
            model_name='servicesignup',
            name='price',
        ),
    ]
