# Generated by Django 4.2 on 2023-05-27 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0004_servicesignup_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_services', to='beauty.salon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='beauty.servicetype'),
        ),
    ]
