# Generated by Django 4.2 on 2023-05-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beauty", "0005_alter_service_salon_alter_service_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="salon",
        ),
    ]
