# Generated by Django 4.2 on 2023-05-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beauty", "0006_remove_service_salon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicesignup",
            name="name",
        ),
        migrations.RemoveField(
            model_name="servicesignup",
            name="phone",
        ),
    ]
